name: test  # default testing environment name from conda-incubator
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - gfortran  # for isitgr
  - pip
  - setuptools
  - setuptools_scm
  - cmake
  - gsl
  - fftw
  - swig
  - pyyaml
  - numpy < 2.4  # fast-pt uses np.trapz, which is deleted in numpy 2.4
  - scipy < 1.14 # velocileptors uses functions removed in recent scipy versions
  - camb
  - fast-pt
  - pytest
  - pytest-cov
  - pytables  # for baccoemu
  - pyfftw  # for velocileptors
  - george  # for dark_emu
  - wheel # for classy
  - cython<3 # for classy
  - pip:
      - classy
      - isitgr
      - velocileptors @ git+https://github.com/sfschen/velocileptors
      - baccoemu @ git+https://bitbucket.org/rangulo/baccoemu.git@master
      - MiraTitanHMFemulator
      - dark_emulator
      - colossus
      
