# -*- coding: utf-8 -*-
#
# Core Cosmology Library documentation build configuration file, created by
# sphinx-quickstart on Sun Dec 17 07:12:51 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import datetime
import importlib
import os
import sys
from os.path import abspath, dirname, join as pjoin

this_dir = dirname(abspath(__file__))
root_path = abspath(pjoin(this_dir, '../'))
if os.path.isdir(root_path):
    sys.path.insert(0, root_path)

on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
if on_rtd:
    try:
        from unittest.mock import MagicMock
    except ImportError:
        from mock import Mock as MagicMock

    class Mock(MagicMock):
        @classmethod
        def __getattr__(cls, name):
            return MagicMock()

    MOCK_MODULES = [
        "pyccl.ccllib",
        "pyccl._types.ccllib",
        "pyccl.background.ccllib",
        "pyccl.bcm.ccllib",
        "pyccl.boltzmann.ccllib",
        "pyccl.halomodel.ccllib",
        "pyccl.haloprofile.ccllib",
        "pyccl.tracers.ccllib",
        "pyccl.constants.ccllib",
        "pyccl.correlation.ccllib",
        "pyccl.neutrinos.ccllib",
        "pyccl.ccllibutils.ccllib",
        "pyccl.cls.ccllib",
        "pyccl.cosmology.ccllib",
        "pyccl.massfunction.ccllib",
        "pyccl.power.ccllib",
        "pyccl.pyutils.ccllib",
        "yaml"]

    sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx_autodoc_typehints',
    'sphinx_mdinclude',
    'sphinxcontrib.bibtex',
]

# Specify bibliography for `spinxcontrib.bibtex`.
bibtex_bibfiles = ['refs.bib']

# Additional `autodoc` options.
autodoc_default_options = {
    "member-order": "bysource",
    "show-inheritance": True,
    "inherited-members": True,
    "special-members": "__call__",
}

# Options for `sphnix_autodoc_typehints`.
typehints_fully_qualified = False
typehints_defaults = "braces"
typehints_document_rtype = False
typehints_use_signature_return = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'pyccl'
year = datetime.datetime.now().year
copyright = f'2018-{year}, LSST DESC'
author = u'LSST DESC'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
# The short X.Y version.
version = u'3.X'
# The full version, including alpha/beta/rc tags.
release = u'3.X.X'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
options = ["sphinx_rtd_theme", "sphinx_book_theme", "pydata_sphinx_theme"]
html_theme = options[1]
html_theme_module = importlib.import_module(html_theme)
try:
    html_theme_path = [html_theme_module.get_html_theme_path()]
except AttributeError:
    pass

html_logo = '../doc/ccl_paper/.logos/desc-logo.png'
html_logo_width = 100
html_logo_height = 100

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []  # ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'CoreCosmologyLibrarydoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc,
     'CoreCosmologyLibrary.tex',
     u'Core Cosmology Library Documentation',
     u'LSST DESC', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc,
     'corecosmologylibrary',
     u'Core Cosmology Library Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'CoreCosmologyLibrary',
     u'Core Cosmology Library Documentation',
     author, 'LSSTDESC', 'Routines for cosmological calculations.',
     'Miscellaneous'),
]


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': (' https://docs.python.org/3', None)}
