name: testing-travis-migration
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: [ 3.6 ]

    steps:
        - uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.py }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.py }}
